package docs.entity;
// Generated 2016-12-26 16:47:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ZtpKlient generated by hbm2java
 */
public class ZtpKlient  implements java.io.Serializable {


     private int idK;
     private String imie;
     private String nazwisko;
     private String nazwa;
     private long nip;
     private Set ztpZamowienies = new HashSet(0);

    public ZtpKlient() {
    }

	
    public ZtpKlient(int idK, String imie, String nazwisko, long nip) {
        this.idK = idK;
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.nip = nip;
    }
    public ZtpKlient(int idK, String imie, String nazwisko, String nazwa, long nip, Set ztpZamowienies) {
       this.idK = idK;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.nazwa = nazwa;
       this.nip = nip;
       this.ztpZamowienies = ztpZamowienies;
    }
   
    public int getIdK() {
        return this.idK;
    }
    
    public void setIdK(int idK) {
        this.idK = idK;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public long getNip() {
        return this.nip;
    }
    
    public void setNip(long nip) {
        this.nip = nip;
    }
    public Set getZtpZamowienies() {
        return this.ztpZamowienies;
    }
    
    public void setZtpZamowienies(Set ztpZamowienies) {
        this.ztpZamowienies = ztpZamowienies;
    }




}


