package docs.entity;
// Generated 2016-12-26 16:47:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ZtpZamowienie generated by hbm2java
 */
public class ZtpZamowienie  implements java.io.Serializable {


     private int idZ;
     private ZtpKlient ztpKlient;
     private byte[] zrealizowane;
     private Set ztpZTs = new HashSet(0);

    public ZtpZamowienie() {
    }

	
    public ZtpZamowienie(int idZ, ZtpKlient ztpKlient, byte[] zrealizowane) {
        this.idZ = idZ;
        this.ztpKlient = ztpKlient;
        this.zrealizowane = zrealizowane;
    }
    public ZtpZamowienie(int idZ, ZtpKlient ztpKlient, byte[] zrealizowane, Set ztpZTs) {
       this.idZ = idZ;
       this.ztpKlient = ztpKlient;
       this.zrealizowane = zrealizowane;
       this.ztpZTs = ztpZTs;
    }
   
    public int getIdZ() {
        return this.idZ;
    }
    
    public void setIdZ(int idZ) {
        this.idZ = idZ;
    }
    public ZtpKlient getZtpKlient() {
        return this.ztpKlient;
    }
    
    public void setZtpKlient(ZtpKlient ztpKlient) {
        this.ztpKlient = ztpKlient;
    }
    public byte[] getZrealizowane() {
        return this.zrealizowane;
    }
    
    public void setZrealizowane(byte[] zrealizowane) {
        this.zrealizowane = zrealizowane;
    }
    public Set getZtpZTs() {
        return this.ztpZTs;
    }
    
    public void setZtpZTs(Set ztpZTs) {
        this.ztpZTs = ztpZTs;
    }




}


