package docs.entity;
// Generated 2016-12-26 16:47:05 by Hibernate Tools 4.3.1



/**
 * ZtpZT generated by hbm2java
 */
public class ZtpZT  implements java.io.Serializable {


     private String id;
     private ZtpTowar ztpTowar;
     private ZtpZamowienie ztpZamowienie;
     private int ilosc;

    public ZtpZT() {
    }

    public ZtpZT(String id, ZtpTowar ztpTowar, ZtpZamowienie ztpZamowienie, int ilosc) {
       this.id = id;
       this.ztpTowar = ztpTowar;
       this.ztpZamowienie = ztpZamowienie;
       this.ilosc = ilosc;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ZtpTowar getZtpTowar() {
        return this.ztpTowar;
    }
    
    public void setZtpTowar(ZtpTowar ztpTowar) {
        this.ztpTowar = ztpTowar;
    }
    public ZtpZamowienie getZtpZamowienie() {
        return this.ztpZamowienie;
    }
    
    public void setZtpZamowienie(ZtpZamowienie ztpZamowienie) {
        this.ztpZamowienie = ztpZamowienie;
    }
    public int getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(int ilosc) {
        this.ilosc = ilosc;
    }




}


